const NikeData = [
    {
        id : 1,
        img:"./assests/Nike1.webp",
        title:"Nike T-shirst New One",
        price:50,
    },
    {
        id : 2,
        img:"./assests/Nike2.webp",
        title:"Nike T-shirst New One",
        price:30,
    },
    {
        id : 3,
        img:"./assests/Nike3.webp",
        title:"Nike T-shirst New One",
        price:42,
    },
    {
        id : 4,
        img:"./assests/Nike4.webp",
        title:"Nike T-shirst New One",
        price:26,
    },
    {
        id : 5,
        img:"./assests/Nike5.webp",
        title:"Nike T-shirst New One",
        price:29,
    },
    {
        id : 6,
        img:"./assests/Nike6.webp",
        title:"Nike T-shirst New One",
        price:24,
    },
    {
        id : 7,
        img:"./assests/Nike7.webp",
        title:"Nike T-shirst New One",
        price:20,
    },
    {
        id : 8,
        img:"./assests/Nike8.webp",
        title:"Nike T-shirst New One",
        price:34,
    },
    {
        id : 9,
        img:"./assests/Nike9.webp",
        title:"Nike T-shirst New One",
        price:41,

    },
    {
        id : 10,
        img:"./assests/Nike10.webp",
        title:"Nike T-shirst New One",
        price:33,
    },
    {
        id : 11,
        img:"./assests/Nike11.webp",
        title:"Nike T-shirst New One",
        price:21,
    },
    {
        id : 12,
        img:"./assests/Nike12.webp",
        title:"Nike T-shirst New One",
        price:26,
    },
    {
        id : 13,
        img:"./assests/Nike13.webp",
        title:"Nike T-shirst New One",
        price:29,
    },
    {
        id : 14,
        img:"./assests/Nike14.webp",
        title:"Nike T-shirst New One",
        price:22,
    },
    {
        id : 15,
        img:"./assests/Nike15.webp",
        title:"Nike T-shirst New One",
        price:24,
    },
    {
        id : 16,
        img:"./assests/Nike16.webp",
        title:"Nike T-shirst New One",
        price:39,
    },
    {
        id : 17,
        img:"./assests/Nike17.webp",
        title:"Nike T-shirst New One",
        price:33,
    },
    {
        id : 18,
        img:"./assests/Nike18.webp",
        title:"Nike T-shirst New One",
        price:31,
    },
    {
        id : 19,
        img:"./assests/Nike19.webp",
        title:"",
        price:43,
    },
    {
        id : 20,
        img:"./assests/Nike20.webp",
        title:"Nike T-shirst New One",
        price:9,
    },
    {
        id : 21,
        img:"./assests/Nike21.webp",
        title:"Nike T-shirst New One",
        price:54,
    },
    {
        id : 22,
        img:"./assests/Nike22.webp",
        title:"Nike T-shirst New One",
        price:20,
    },
    {
        id : 23,
        img:"./assests/Nike23.webp",
        title:"Nike T-shirst New One",
        price:51,
    },
    {
        id : 24,
        img:"./assests/Nike24.webp",
        title:"Nike T-shirst New One",
        price:30,
    },
    {
        id : 25,
        img:"./assests/Nike25.webp",
        title:"Nike T-shirst New One",
        price:31,
    },
    {
        id : 26,
        img:"./assests/Nike26.webp",
        title:"Nike T-shirst New One",
        price:41,
    },
    {
        id : 27,
        img:"./assests/Nike27.webp",
        title:"Nike T-shirst New One",
        price:28,
    },
    {
        id : 28,
        img:"./assests/Nike28.webp",
        title:"Nike T-shirst New One",
        price:12,
    },
   
]
export default NikeData;